# Generated by Django 5.1.4 on 2024-12-23 13:24

import django.contrib.postgres.functions
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.contrib.postgres.functions.TransactionNow()
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("note", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("checking", "Checking"),
                            ("loans_receivable", "Loans receivable"),
                            ("credit_card", "Credit card"),
                            ("discount_allowed", "Discount allowed"),
                        ],
                        default="Checking",
                        max_length=16,
                    ),
                ),
                ("normal", models.IntegerField(choices=[(1, "Debit"), (-1, "Credit")])),
                ("balance", models.IntegerField(default=0)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                ("date_closed", models.DateTimeField()),
                ("balance", models.IntegerField()),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionLeg",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("normal", models.IntegerField(choices=[(1, "Debit"), (-1, "Credit")])),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transaction_details",
                        to="ledger.account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="details",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
