# Generated by Django 5.1.4 on 2024-12-23 13:25

from django.db import migrations
from django_bulla.models.normals import Normals


def add_top_level_accounts(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    Account.objects.create(name="Dividends", normal=Normals.DEBIT)
    Account.objects.create(name="Expenses", normal=Normals.DEBIT)
    Account.objects.create(name="Assets", normal=Normals.DEBIT)
    Account.objects.create(name="Liabilities", normal=Normals.CREDIT)
    Account.objects.create(name="Equity", normal=Normals.CREDIT)
    Account.objects.create(name="Revenue", normal=Normals.CREDIT)


def remove_top_level_accounts(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    Account.objects.filter(name="Dividends").delete()
    Account.objects.filter(name="Expenses").delete()
    Account.objects.filter(name="Assets").delete()
    Account.objects.filter(name="Liabilities").delete()
    Account.objects.filter(name="Equity").delete()
    Account.objects.filter(name="Revenue").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_top_level_accounts, reverse_code=remove_top_level_accounts
        )
    ]
